# Generated by Django 4.2.1 on 2023-05-07 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('year', models.PositiveIntegerField(help_text='Формат даты: <ГГГГ>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год релиза')),
            ],
            options={
                'ordering': ['artist', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('JAZZ', 'Jazz'), ('HIPHOP', 'Hip hop'), ('ROCK', 'Rock'), ('POP', 'Popular music'), ('ELECTRO', 'Electronic')], max_length=8, verbose_name='genre')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.SmallIntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='discography.album')),
            ],
            options={
                'ordering': ['track_number'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discography.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='discography.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='discography.artist'),
        ),
    ]
