# Generated by Django 4.2 on 2023-05-03 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('JAZZ', 'Jazz'), ('HIPHOP', 'Hip hop'), ('ROCK', 'Rock'), ('POP', 'Popular music'), ('ELECTRO)', 'Electronic')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(help_text='Формат даты: <ГГГГ>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год релиза')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discography.artist')),
                ('genre', models.ManyToManyField(to='discography.genre')),
            ],
            options={
                'ordering': ['artist', 'year'],
            },
        ),
    ]
