# Generated by Django 4.2.1 on 2023-05-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='discography.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
