# Generated by Django 4.2 on 2023-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(choices=[('JAZZ', 'Jazz'), ('HIPHOP', 'Hip hop'), ('ROCK', 'Rock'), ('POP', 'Popular music'), ('ELECTRO', 'Electronic')], max_length=8, verbose_name='genre'),
        ),
    ]
