# Generated by Django 4.2.1 on 2023-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0006_alter_genre_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-track_number']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
