# Generated by Django 4.2.1 on 2023-05-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0018_alter_track_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['track_number']},
        ),
    ]
