# Generated by Django 4.2.1 on 2023-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0020_artist_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(null=True, upload_to='artist', verbose_name='Фото Артиста'),
        ),
    ]
