# Generated by Django 4.2.1 on 2023-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0021_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='album', verbose_name='Обложка Альбома'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artist', verbose_name='Фото Артиста'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='Профиль артиста'),
        ),
    ]
