# Generated by Django 4.2.1 on 2023-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0022_album_photo_alter_artist_photo_alter_artist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, default='album/vinyl.png', null=True, upload_to='album', verbose_name='Обложка Альбома'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, default='artist/singer.png', null=True, upload_to='artist', verbose_name='Фото Артиста'),
        ),
    ]
