# Generated by Django 4.2.1 on 2023-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0025_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
