# Generated by Django 4.2.1 on 2023-05-13 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0027_alter_album_artist_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(related_name='albums', to='discography.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(default='album/vinyl.png', upload_to='album', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Год релиза'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(default='artist/singer.png', upload_to='artist', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(choices=[('Jazz', 'Jazz'), ('Hip Hop', 'Hip hop'), ('Rock', 'Rock'), ('Pop', 'Popular music'), ('Electronic', 'Electronic')], max_length=255, verbose_name='Жанр'),
        ),
    ]
