# Generated by Django 4.2.1 on 2023-05-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0028_alter_album_genre_alter_album_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
