# Generated by Django 4.2.1 on 2023-05-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0030_alter_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='discography.artist', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='discography.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='discography.artist', verbose_name='Артист'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(max_length=255, null=True, verbose_name='Длина'),
        ),
    ]
