# Generated by Django 4.2.1 on 2023-05-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0038_alter_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.TextField(blank=True, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
