# Generated by Django 4.2.1 on 2023-05-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0040_alter_artist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('artist', 'year')},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('track_number',)},
        ),
    ]
