# Generated by Django 4.2.1 on 2023-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0049_alter_review_options_alter_artist_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, default='album/vinyl.png', upload_to='album', verbose_name='Обложка'),
        ),
    ]
