# Generated by Django 4.2.1 on 2023-06-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0050_alter_album_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, upload_to='album', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='artist', verbose_name='Фото'),
        ),
    ]
